spring.application.name=Diary
server.port=${PORT:8080}
server.address=0.0.0.0
spring.datasource.url=${SPRING_DATABASE_URL}
spring.datasource.username=${SPRING_DATABASE_USERNAME}
spring.datasource.password=${SPRING_DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
