spring.application.name=Diary
server.port=9090
spring.datasource.url=${SPRING_DATABASE_URL}
spring.datasource.username=${SPRING_DATABASE_USERNAME}
spring.datasource.password=${SPRING_DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
