spring.application.name=Diary
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/diary
spring.datasource.username=postgres
spring.datasource.password=1012
spring.jpa.hibernate.ddl-auto=update